app/home/__init__.py
from flask import Blueprint

home = Blueprint(
    'home',
    __name__,
    template_folder='templates',
    static_folder='static'
)

from . import views

app/home/views.py
from flask import render_template
from flask_login import current_user
from . import home

@home.route('/')
def homepage():
    return render_template('content.html')

app/home/templates/body.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block styles %}
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        {{ bootstrap.load_css() }}
        {% endblock %}

        <title>{% block title %}{{ config.NAME }}{% endblock %}</title>
        {% endblock %}
    </head>
    <body>

        {% from 'bootstrap/nav.html' import render_nav_item %}

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{{ url_for('home.homepage') }}">{{ config.NAME }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav mr-auto">
                    {{ render_nav_item('home.homepage','Home') }}
                    {{ render_nav_item('console.consolepage','Codes') }}
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                    <span class="navbar-text">
                        <i>{{ current_user.username }}</i>
                    </span>
                    {% if current_user.is_admin() %}
                    {{ render_nav_item('console.admin', 'Admin') }}
                    {% endif %}
                    {{ render_nav_item('oauth.logout', 'Logout') }}
                    {% else %}
                    {{ render_nav_item('oauth.login', 'Login via HQ Platform') }}
                    {% endif %}
                </ul>
            </div>
        </nav>
        <br />
        <div class="container">
            {% from 'bootstrap/utils.html' import render_messages %}
            {{ render_messages() }}

            {% block content %}{% endblock %}
        </div>
        {% block scripts %}
        <!-- Optional JavaScript -->
        {{ bootstrap.load_js() }}
        {% endblock %}
    </body>
</html>

app/home/templates/content.html
{% extends "body.html" %}
{% block title %}{{ config.NAME }} - Home{% endblock %}
{% block content %}
<div class="jumbotron">
    <h1 class="display-4">{{ config.NAME }}</h1>
    <p class="lead">{{ config.NAME}} is our platform for generating and distributing our partners licence keys, discount codes and free credit.</p>
    <hr class="my-4">
    <p>
        Just login with you Platform account and you'll be able to access their wide variety of tools!
    </p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="{{ url_for('oauth.login') }}" role="button">Login now</a>
    </p>
</div>
{% endblock %}